---
namespace: check_point
name: gaia
version: 7.0.0
readme: README.md
authors:
  - Majd Sharkia <majds@checkpoint.com>
  - Ameer Asli <ameera@checkpoint.com>
description: Check Point collection for managing a Check Point machine configurations.
license:
  - GPL-3.0-or-later
license_file: LICENSE
tags:
  - security
dependencies:
  ansible.netcommon: "*"
repository: https://github.com/CheckPointSW/CheckPointAnsibleGAIACollection
documentation: https://galaxy.ansible.com/ui/repo/published/check_point/gaia/docs/
homepage: https://github.com/CheckPointSW/CheckPointAnsibleGAIACollection
issues: https://github.com/CheckPointSW/CheckPointAnsibleGAIACollection/issues
